
language: c
os: linux
dist: trusty

cache:
  directories:
    - $HOME/cistore


compiler:
  - gcc

branches:
  only:
    - master


before_script:
  - chmod +x travis.linux.sh
  - chmod +x travis.mac.sh
  - chmod +x build.linux.sh
  - chmod +x build.mac.sh
  - chmod +x prereqs.sh


jobs:
  allow_failures:
  - os: osx
  include:
    - stage: build
      script: ./travis.linux.sh
      os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - libgnutls-openssl27
            - libgnutls30
    - stage: build
      script: ./travis.mac.sh
      osx_image: xcode12.2
      os: osx


after_success:
  - echo "Build and tests successful."

after_failure:
  - echo "Build and tests failed."

